export const CHARACTERS_FETCH_LIST = "CHARACTERS_FETCH_LIST"
export const CHARACTERS_SET_FETCHING = "CHARACTERS_SET_FETCHING"
export const CHARACTERS_UPDATE_SELECTED_ITEM = "CHARACTERS_UPDATE_SELECTED_ITEM"